# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88f5a95a9841d3bb00c8465eb01beef605b9f9da5c82766daa53f82156af20b539f185183a76a27925081300771bbd9ddb96d75329cac8864f759c06967af2a

test:
  secret_key_base: ecd13e2458a8ffde7a4f0bdd7e24525acd1528e64bea95b59d6805fb9929d97fd3fd22b16c81651678859d6f3a9bf17465c26e6e70850750effa0fdc068e7f27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
